---
name: Setup
description: Setup Release Train & dependencies
inputs:
  vault-password:
    description: Ansible Vault password
    required: true
    type: string
  vault-password-file:
    description: Path to a file to write the Ansible Vault password
    required: true
    type: string
runs:
  using: composite
  steps:

    - name: Preparing Vault password file
      run: |
        echo "${{ inputs.vault-password }}" > "${{ inputs.vault-password-file }}"
      shell: bash

    - name: Install Python dependencies
      run: >
        sudo apt update &&
        sudo apt -y install python3 python3-pip &&
        pip install -r requirements.txt
      shell: bash

    - name: Install Ansible collection dependencies
      run: |
        ansible-galaxy collection install -r requirements.yml -p ansible/collections
      shell: bash
