---
collections:
  - name: https://github.com/stackhpc/ansible-collection-pulp.git
    type: git
    version: master
  - name: community.crypto
    version: 2.0.2
  - name: pulp.squeezer
    version: 0.2.3
