---
# This playbook queries the Pulp repository versions defined in a Kayobe
# configuration repository (in etc/kayobe/pulp-repo-versions.yml). It then sets
# the 'dev_pulp_distribution_rpm_promote_versions' version map variable based
# upon those versions, which defines the set of repository versions that will
# be promoted when the dev-pulp-repo-promote.yml playbook is run.

- name: Import kayobe-repo-version-query playbook
  import_playbook: kayobe-repo-version-query.yml

- name: Set dev Pulp repo versions to promote from Kayobe config versions
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Set a fact about rpm versions to promote
      ansible.builtin.set_fact:
        dev_pulp_distribution_rpm_promote_versions: >-
          {{ dev_pulp_distribution_rpm_promote_versions |
             default({}) |
             combine({item.short_name: kayobe_pulp_repo_versions[item.short_name]}) }}
      loop: "{{ dev_pulp_distribution_rpm_promote }}"
      loop_control:
        label: "{{ item.short_name }}"
      when: item.short_name in kayobe_pulp_repo_versions

    - name: Set a fact about deb versions to promote
      ansible.builtin.set_fact:
        dev_pulp_distribution_deb_promote_versions: >-
          {{ dev_pulp_distribution_deb_promote_versions |
             default({}) |
             combine({item.short_name: kayobe_pulp_repo_versions[item.short_name]}) }}
      loop: "{{ dev_pulp_distribution_deb_promote }}"
      loop_control:
        label: "{{ item.short_name }}"
      when: item.short_name in kayobe_pulp_repo_versions

    - name: Display rpm promotion versions facts
      ansible.builtin.debug:
        var: dev_pulp_distribution_rpm_promote_versions

    - name: Display deb promotion versions facts
      ansible.builtin.debug:
        var: dev_pulp_distribution_deb_promote_versions

    - name: Assert that versions variable is populated
      ansible.builtin.assert:
        that:
          - >-
            dev_pulp_distribution_deb_promote_versions | length > 0 or
            dev_pulp_distribution_rpm_promote_versions | length > 0
        msg: >-
          Distribution promotion version variables
          'dev_pulp_distribution_deb_promote_versions' and
          'dev_pulp_distribution_rpm_promote_versions' are empty
