---
# Promote a set of development repositories to releases.
#
# The distribution versions promoted are those defined in
# the 'dev_pulp_distribution_deb_promote_versions' and
# 'dev_pulp_distribution_rpm_promote_versions version map variables. This
# should be specified via an extra variables file.
# The content guard for those distributions will be updated from 'development'
# to 'release'.

- name: Promote dev Pulp distributions
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Assert that a versions variable is populated
      assert:
        that:
          - >-
            dev_pulp_distribution_deb_promote_versions | length > 0 or
            dev_pulp_distribution_rpm_promote_versions | length > 0
        msg: >-
          Distribution promotion version variables
          'dev_pulp_distribution_deb_promote_versions' and
          'dev_pulp_distribution_rpm_promote_versions' are empty

    # We want to update existing distributions here, so omit the 'publication'
    # parameter.
    - name: Ensure Deb distributions are promoted
      pulp.squeezer.deb_distribution:
        pulp_url: "{{ dev_pulp_url }}"
        username: "{{ dev_pulp_username }}"
        password: "{{ dev_pulp_password }}"
        name: "{{ item.name }}"
        base_path: "{{ item.base_path }}"
        content_guard: "{{ item.content_guard }}"
        state: "{{ item.state }}"
      loop: "{{ dev_pulp_distribution_deb_promote | selectattr('short_name', 'in', dev_pulp_distribution_deb_promote_versions.keys()) | list }}"
      register: pulp_rpm_promotion
      until: "pulp_rpm_promotion is not failed"
      retries: 3
      delay: 1

    - name: Ensure RPM distributions are promoted
      pulp.squeezer.rpm_distribution:
        pulp_url: "{{ dev_pulp_url }}"
        username: "{{ dev_pulp_username }}"
        password: "{{ dev_pulp_password }}"
        name: "{{ item.name }}"
        base_path: "{{ item.base_path }}"
        content_guard: "{{ item.content_guard }}"
        state: "{{ item.state }}"
      loop: "{{ dev_pulp_distribution_rpm_promote | selectattr('short_name', 'in', dev_pulp_distribution_rpm_promote_versions.keys()) | list }}"
      register: pulp_deb_promotion
      until: "pulp_deb_promotion is not failed"
      retries: 3
      delay: 1
