---
- name: Ensure dev and release content guards exist
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Run stackhpc.pulp.pulp_content_guard role
      ansible.builtin.import_role:
        name: stackhpc.pulp.pulp_content_guard
      vars:
        pulp_url: "{{ dev_pulp_url }}"
        pulp_username: "{{ dev_pulp_username }}"
        pulp_password: "{{ dev_pulp_password }}"
        pulp_content_guard_rbac: "{{ dev_pulp_content_guards_rbac }}"
