---
# This playbook queries the Pulp container image tags defined in a Kayobe
# configuration repository (in etc/kayobe/kolla-image-tags.yml). It then sets
# the 'kayobe_pulp_container_tags' tag map variable based upon those tags.
#
# The kayobe-config repository path should be specified via
# kayobe_config_repo_path.

- name: Query container image tags for Kayobe
  hosts: localhost
  gather_facts: true
  vars:
    kayobe_config_repo_path: ""
  tasks:
    - name: Fail if Kayobe config repo path is not specified
      ansible.builtin.fail:
        msg: >
          Kayobe config git repository path must be specified via 'kayobe_config_repo_path'.
      when: not kayobe_config_repo_path

    - name: Fail if Kayobe config repo path is not a directory
      ansible.builtin.fail:
        msg: >
          Kayobe config git repository path {{ kayobe_config_repo_path }} is not a directory.
      when: kayobe_config_repo_path is not directory

    - name: List Kayobe Kolla image tags
      ansible.builtin.command:
        cmd: >-
          {{ kayobe_config_repo_path | realpath }}/tools/kolla-images.py list-tags
        chdir: "{{ kayobe_config_repo_path | realpath }}"
      register: list_tags
      check_mode: false
      changed_when: false

    - name: Set a fact about Kayobe Kolla image tags
      ansible.builtin.set_fact:
        kayobe_kolla_image_tags: "{{ list_tags.stdout | from_yaml }}"

    - name: Display Kayobe Kolla image tags
      ansible.builtin.debug:
        var: kayobe_kolla_image_tags
