---
# This playbook tests the latests test repositories.
# * configure DNF to use the latest test repositories
# * update all packages
# * distro sync
# * install a package from each repository

- name: Test test repositories
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Install keys for test repositories
      become: true
      ansible.builtin.rpm_key:
        key: "{{ item }}"
      loop:
        - https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Cloud
        - https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-NFV
        - https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-OpsTools
        - https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Storage
        - https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-Virtualization
      when:
        - ansible_facts.os_family == 'RedHat'

    - name: Install test repositories
      become: true
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.repository }}"
        baseurl: "{{ test_pulp_url ~ '/pulp/content/' ~ item.base_path }}"
      loop: "{{ test_pulp_distribution_rpm }}"
      when:
        - ansible_facts.os_family == 'RedHat'
        # FIXME: clashes with docker
        - "'docker' not in item.name"

    - name: Run package update
      become: true
      ansible.builtin.package:
        name: "*"
        state: latest # noqa package-latest

    - name: Run DNF distro-sync
      become: true
      ansible.builtin.command:
        cmd: dnf distro-sync
      when: ansible_facts.os_family == 'RedHat'

    - name: Install packages
      become: true
      ansible.builtin.package:
        name: "{{ item.packages }}"
      loop:
        - repo: CentOS Stream 8 - BaseOS
          packages:
            - dos2unix
        - repo: CentOS Stream 8 - AppStream
          packages:
            - bind
        - repo: CentOS Stream 8 - Extras
          packages:
            - centos-release-advanced-virtualization
        - repo: Extra Packages for Enterprise Linux 8 - x86_64
          packages:
            - smem
        - repo: Extra Packages for Enterprise Linux Modular 8 - x86_64
          packages:
            - swig
        # FIXME: clashes with docker
        - repo: Docker CE for CentOS 8
          packages: []
