---
# Due to a bug in Pulp (https://github.com/pulp/pulp_rpm/issues/2311), we can
# end up with multiple publications for a single repository version after
# performing a sync. This breaks assumptions in the Pulp squeezer modules about
# uniqueness, causing the rpm_publication module to fail, and breaking sync
# jobs.
#
# This playbook looks for repository versions with multiple publications, and
# removes the most recent.

- name: Clean up duplicate publications
  hosts: localhost
  gather_facts: true
  vars:
    pulp_url: "{{ test_pulp_url }}"
    pulp_username: "{{ test_pulp_username }}"
    pulp_password: "{{ test_pulp_password }}"
  tasks:
    - name: Query repositories
      pulp.squeezer.rpm_repository:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_repos_list

    - name: Query publications
      pulp.squeezer.rpm_publication:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_pubs_list

    - name: Query distributions
      pulp.squeezer.rpm_distribution:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_dists_list

    - vars:
        repo: "{{ pulp_repos_list.repositories | selectattr('name', 'equalto', item.repository) | first }}"
        pubs: "{{ pulp_pubs_list.publications | selectattr('repository_version', 'equalto', repo.latest_version_href) }}"
      block:
        - name: Show duplicate publications
          ansible.builtin.debug:
            msg: "{{ pubs | sort(attribute='pulp_created') }}"
          loop: "{{ test_pulp_distribution_rpm }}"
          loop_control:
            label: "{{ item.repository }}"
          when: pubs | length > 1

        - name: Fail if duplicate publications have distributions
          ansible.builtin.assert:
            that: dists | length == 0
          loop: "{{ test_pulp_distribution_rpm }}"
          loop_control:
            label: "{{ item.repository }}"
          when: pubs | length > 1
          vars:
            duplicate_pub: "{{ pubs | sort(attribute='pulp_created') | last }}"
            dists: "{{ pulp_dists_list.distributions | selectattr('publication', 'equalto', duplicate_pub.pulp_href) }}"

        # Use URI module since pulp.squeezer.rpm_publication fails if there are
        # multiple matching publications.
        - name: Destroy duplicate publications
          ansible.builtin.uri:
            url: "{{ pulp_url }}{{ duplicate_pub.pulp_href }}"
            user: "{{ pulp_username }}"
            password: "{{ pulp_password }}"
            method: DELETE
            status_code: 204
            force_basic_auth: true
          loop: "{{ test_pulp_distribution_rpm }}"
          loop_control:
            label: "{{ item.repository }}"
          when: pubs | length > 1
          vars:
            duplicate_pub: "{{ pubs | sort(attribute='pulp_created') | last }}"
