---
- name: Sync test Pulp repositories
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Assert that Deb versions variable is populated
      ansible.builtin.assert:
        that:
          - missing_repos | length == 0
        msg: >-
          Some expected Deb repositories not present in sync versions: {{ missing_repos | join(',') }}
      vars:
        missing_repos: "{{ test_pulp_repository_deb_repos | map(attribute='short_name') | list | difference(test_pulp_repository_deb_repo_versions) | list }}"
      when: not test_pulp_sync_repo_version

    - name: Assert that RPM versions variable is populated
      ansible.builtin.assert:
        that:
          - missing_repos | length == 0
        msg: >-
          Some expected RPM repositories not present in sync versions: {{ missing_repos | join(',') }}
      vars:
        missing_repos: "{{ test_pulp_repository_rpm_repos | map(attribute='short_name') | list | difference(test_pulp_repository_rpm_repo_versions) | list }}"
      when: not test_pulp_sync_repo_version

    - ansible.builtin.import_role:
        name: stackhpc.pulp.pulp_repository
      vars:
        pulp_url: "{{ test_pulp_url }}"
        pulp_username: "{{ test_pulp_username }}"
        pulp_password: "{{ test_pulp_password }}"
        pulp_repository_deb_repos: "{{ test_pulp_repository_deb_repos }}"
        pulp_repository_rpm_repos: "{{ test_pulp_repository_rpm_repos }}"
