name: Pull Request Stats

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        id: stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          organization: 'stackhpc'
          period: 90
          charts: true
          #disableLinks: true
          sortBy: 'COMMENTS'

      - name: Display markdown
        run: echo '${{ steps.stats.outputs.resultsMd }}'
